# -*- coding: utf-8 -*-
"""ML_2-3_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6XH2FdsJwxWBIXZTdzcQGCK4wKFr80u
"""

print("hello world!")
print("test test")